In [5]:
import pandas as pd
import numpy as np
import mysql.connector

### 建立技優DataToDB

In [48]:
dfAchievement = pd.read_excel("./文件集/技優類別統整.xlsx")
dfAchievement['類別ID'] = dfAchievement['類別ID'].astype('str')

In [50]:
data = []
for i in range(len(dfAchievement)):
    data.append((dfAchievement.iloc[i][0], dfAchievement.iloc[i][1]))
data

[('10', '機械'),
 ('12', '農機'),
 ('15', '汽車'),
 ('20', '電機'),
 ('21', '冷凍'),
 ('25', '電子'),
 ('26', '電訊'),
 ('30', '化工'),
 ('33', '紡織'),
 ('34', '紡化'),
 ('35', '衛生'),
 ('40', '土木'),
 ('41', '農土'),
 ('44', '輪機'),
 ('45', '航運'),
 ('46', '漁業'),
 ('47', '水產養殖'),
 ('50', '護理'),
 ('55', '工程'),
 ('56', '管理'),
 ('60', '商業'),
 ('62', '航管'),
 ('65', '資管'),
 ('70', '園藝'),
 ('71', '畜牧'),
 ('72', '農場經營'),
 ('73', '林產(甲)'),
 ('74', '林產(乙)'),
 ('76', '家政'),
 ('77', '服裝'),
 ('78', '美容'),
 ('79', '餐旅'),
 ('80', '工設'),
 ('85', '商設'),
 ('90', '食品'),
 ('91', '水產製造'),
 ('95', '幼保'),
 ('96', '資安')]

In [51]:
conn = mysql.connector.connect(user='root', password='root', host='localhost', database='四技二專')
cursor = conn.cursor()
sql = "insert into 技優 values(%s, %s, null)"
cursor.executemany(sql, data)
conn.commit()

In [52]:
cursor.close()
conn.close()

### 彙整112技優類別Excel

In [2]:
dfRec = pd.read_excel("./文件集/112技優甄選.xls")
dfConveyed = pd.read_excel('./文件集/112技優保送.xls')
print(dfRec['類別代碼'].unique(), len(dfRec['類別代碼'].unique()))
dfConveyed['類別代碼'].unique(), len(dfConveyed['類別代碼'].unique())

['10機械' '20電機' '25電子' '30化工' '40土木' '60商業' '65資管' '80工設' '85商設' '12農機'
 '15汽車' '47水產養殖' '55工程' '56管理' '70園藝' '71畜牧' '72農場經營' '73林產(甲)' '74林產(乙)'
 '77服裝' '78美容' '90食品' '95幼保' '34紡化' '26電訊' '35衛生' '44輪機' '46漁業' '62航管'
 '79餐旅' '91水產製造' '21冷凍' '76家政' '50護理'] 34

(array(['10機械', '20電機', '25電子', '30化工', '40土木', '60商業', '65資管', '76家政',
        '80工設', '85商設', '12農機', '15汽車', '47水產養殖', '55工程', '56管理', '70園藝',
        '71畜牧', '72農場經營', '73林產(甲)', '74林產(乙)', '77服裝', '78美容', '90食品',
        '95幼保', '21冷凍', '44輪機', '45航運', '46漁業', '62航管', '91水產製造', '79餐旅'],
       dtype=object),
 31)

In [3]:
temp = np.append(np.sort(dfRec['類別代碼'].unique()), np.sort(dfConveyed['類別代碼'].unique()))
classes = np.unique(temp)
classes, len(classes), type(classes)

(array(['10機械', '12農機', '15汽車', '20電機', '21冷凍', '25電子', '26電訊', '30化工',
        '34紡化', '35衛生', '40土木', '44輪機', '45航運', '46漁業', '47水產養殖', '50護理',
        '55工程', '56管理', '56管理', '60商業', '62航管', '65資管', '70園藝', '71畜牧',
        '72農場經營', '73林產(甲)', '74林產(乙)', '76家政', '77服裝', '78美容', '79餐旅',
        '79餐旅', '80工設', '85商設', '90食品', '91水產製造', '95幼保'], dtype=object),
 37,
 numpy.ndarray)

In [13]:
achievement_adm_data = []
for group in classes:
    achievement_adm_data.append([group[:2], group[2:]])
achievement_adm_data

[['10', '機械'],
 ['12', '農機'],
 ['15', '汽車'],
 ['20', '電機'],
 ['21', '冷凍'],
 ['25', '電子'],
 ['26', '電訊'],
 ['30', '化工'],
 ['34', '紡化'],
 ['35', '衛生'],
 ['40', '土木'],
 ['44', '輪機'],
 ['45', '航運'],
 ['46', '漁業'],
 ['47', '水產養殖'],
 ['50', '護理'],
 ['55', '工程'],
 ['56', '管理'],
 ['56', '管理'],
 ['60', '商業'],
 ['62', '航管'],
 ['65', '資管'],
 ['70', '園藝'],
 ['71', '畜牧'],
 ['72', '農場經營'],
 ['73', '林產(甲)'],
 ['74', '林產(乙)'],
 ['76', '家政'],
 ['77', '服裝'],
 ['78', '美容'],
 ['79', '餐旅'],
 ['79', '餐旅'],
 ['80', '工設'],
 ['85', '商設'],
 ['90', '食品'],
 ['91', '水產製造'],
 ['95', '幼保']]

In [19]:
dfAchievement = pd.DataFrame(achievement_adm_data, columns=['類別ID', '類別名稱'])
dfAchievement = dfAchievement.drop(17).reset_index(drop=True)
dfAchievement

   類別ID   類別名稱
0    10     機械
1    12     農機
2    15     汽車
3    20     電機
4    21     冷凍
5    25     電子
6    26     電訊
7    30     化工
8    34     紡化
9    35     衛生
10   40     土木
11   44     輪機
12   45     航運
13   46     漁業
14   47   水產養殖
15   50     護理
16   55     工程
17   56     管理
18   60     商業
19   62     航管
20   65     資管
21   70     園藝
22   71     畜牧
23   72   農場經營
24   73  林產(甲)
25   74  林產(乙)
26   76     家政
27   77     服裝
28   78     美容
29   79     餐旅
30   79     餐旅
31   80     工設
32   85     商設
33   90     食品
34   91   水產製造
35   95     幼保

In [20]:
dfAchievement.to_excel("./文件集/技優類別統整.xlsx", index=False)